spring:
  cloud:
    gateway:
      routes:
        - id: test1
          uri: http://localhost:7001
          predicates:
            - Path=/api1/**
          filters:
            - RewritePath=/api1/(?<path>.*),/$\{path}
        - id: test2
          uri: http://localhost:7002
          predicates:
            - Path=/api2/**
          filters:
            - RewritePath=/api2/(?<path>.*),/$\{path}
        - id: test3
          uri: http://localhost:7003
          predicates:
            - Path=/api3/**
          filters:
            - RewritePath=/api3/(?<path>.*),/$\{path}